env:
  browser: true
  es2021: true
extends:
  - "eslint:recommended"
  - "plugin:vue/vue3-essential"
  - "plugin:@typescript-eslint/recommended"
parser: "vue-eslint-parser"
parserOptions:
  ecmaVersion: 12
  parser: "@typescript-eslint/parser"
plugins:
  - vue
  - "@typescript-eslint"
rules:
  quotes:
    - 1
    - single
  semi:
    - 1
    - never
